import '@/styles/globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

const font = localFont({
  src: '../lib/assets/font/rdp.ttf',
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  )
}
